### ISSUE TITLE
Beaver Creek Crozet migration QA

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#780]
Appears that facility model will not run in mode 6, but OK in mode 4?
- Facility: om-model-info/4829113

#### Debugging
See also: https://github.com/HARPgroup/HSPsquared/issues/61
- Note: Beaver Creek is a sub-waterxshed, but configured to run stand-alone, and therefore will be cached if running from Mechums.  Thus, in order ot see actual changes you must run Beaver Creek, or clear it's results or use a cache date that forces its rerun!
- used file: https://github.com/HARPgroup/HSPsquared/blob/devstateom/tests/testcbp/HSP2results/test_object_json.py
- Made `el_pid` declaration to `el_pid = 4829113` 
- Made river_pid declaration `river_pid = 4431664`

```
river_pid = 4431664
el_pid = 4829113

odebug = model_object_cache["/STATE/RCHRES_R001/CROZET WTP:Beaver Creek Reservoir/base_demand_pstatus_mgd"]

odebug = model_object_cache["/STATE/RCHRES_R001/CROZET WTP:Beaver Creek Reservoir/consumption_monthly"]

```

**Comment by rburghol** [comment]
Testing/debugging matrix loaders:
```
odebug = model_object_cache["/STATE/RCHRES_R001/CROZET WTP:Beaver Creek Reservoir/consumption_monthly"]
>>> odebug
<HSP2.om_data_matrix.DataMatrix object at 0x000001CF812B5600>
>>> odebug.find_paths()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\usr\local\home\git\HSPsquared\HSP2\om_data_matrix.py", line 120, in find_paths
    el_value = self.matrix[i][j]
IndexError: index 12 is out of bounds for axis 0 with size 12
>>>

```

Load the river, so that run_mode and flow_mode are present:
```
river_pid = 4431664
json_url = src_json_node + "/" + str(river_pid)
jraw =  requests.get(json_url, auth=basic)
river_json = jraw.content.decode('utf-8')
# returns JSON object as Dicts
river_data = json.loads(river_json )
river_name = list(river_data.keys())[0]
model_data = {}
model_data['RCHRES_R001'] = river_data[river_name]

model_data['RCHRES_R001']['name'] = 'RCHRES_R001'
model_data['RCHRES_R001']['object_class'] = 'ModelObject'
model_data['RCHRES_R001'][fac_name] = fac_model

# save the json to a file
with open("C:/usr/local/home/git/HSPsquared/tests/testcbp/HSP2results/PL3_5250_0001.json", "w") as river_file:
    json.dump(model_data, river_file, indent=4, sort_keys=True)

container = False 

```

**Comment by rburghol** [comment]
```

odb = model_object_cache["/STATE/RCHRES_R001/Listen to Children"]



```

**Comment by rburghol** [comment]
See here for channel Object development https://github.com/HARPgroup/HSPsquared/issues/77
